'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { 
  FileTextIcon, 
  LightbulbIcon, 
  Wand2Icon,
  ArrowLeftIcon
} from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function NewContentPage() {
  const router = useRouter();
  const [contentType, setContentType] = useState<'article' | 'product' | 'campaign'>('article');
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!title.trim()) {
      alert('Please enter a title');
      return;
    }

    setIsGenerating(true);
    try {
      // Simulate AI content generation
      setTimeout(() => {
        const generatedContent = `This is a sample ${contentType} about "${title}". 

In a real implementation, this would be generated by AI based on your title and preferences. The content would be tailored to your brand voice and include relevant SEO optimization.

Key points about this ${contentType}:
- It addresses the main topic effectively
- It's structured for readability
- It includes relevant keywords and phrases
- It matches your specified brand voice

This is just a placeholder to demonstrate the functionality. In the actual application, this would connect to the AI service to generate high-quality, original content.`;
        
        setContent(generatedContent);
        setIsGenerating(false);
      }, 2000);
    } catch (error) {
      console.error('Generation failed:', error);
      setIsGenerating(false);
      alert('Failed to generate content');
    }
  };

  const handleSave = () => {
    // Save to localStorage for demo
    const savedContent = JSON.parse(localStorage.getItem('content_library') || '[]');
    const newContent = {
      id: Date.now().toString(),
      title,
      content,
      type: contentType.toUpperCase(),
      status: 'draft',
      createdAt: new Date().toISOString(),
    };
    
    savedContent.push(newContent);
    localStorage.setItem('content_library', JSON.stringify(savedContent));
    
    alert('Content saved to library!');
    router.push('/content');
  };

  return (
    <div className="container mx-auto py-8 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Button variant="ghost" size="sm" onClick={() => router.back()}>
            <ArrowLeftIcon className="h-4 w-4 mr-2" />
            Back
          </Button>
          <div>
            <h1 className="text-3xl font-bold">Create New Content</h1>
            <p className="text-muted-foreground">
              Generate AI-powered content for your websites
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Input Form */}
          <div className="lg:col-span-1">
            <Card className="sticky top-6">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <LightbulbIcon className="h-5 w-5" />
                  Content Brief
                </CardTitle>
                <CardDescription>
                  Tell the AI what you want to create
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="contentType">Content Type</Label>
                  <Select value={contentType} onValueChange={(value: any) => setContentType(value)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Select content type" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="article">Article</SelectItem>
                      <SelectItem value="product">Product Description</SelectItem>
                      <SelectItem value="campaign">Campaign</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="title">Title / Topic</Label>
                  <Input
                    id="title"
                    placeholder="e.g., The Future of Renewable Energy"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="keywords">Keywords (optional)</Label>
                  <Input
                    id="keywords"
                    placeholder="solar, wind, sustainable energy"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="tone">Writing Tone</Label>
                  <Select defaultValue="professional">
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="professional">Professional</SelectItem>
                      <SelectItem value="casual">Casual</SelectItem>
                      <SelectItem value="friendly">Friendly</SelectItem>
                      <SelectItem value="formal">Formal</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <Button 
                  onClick={handleGenerate} 
                  disabled={isGenerating || !title.trim()}
                  className="w-full"
                >
                  {isGenerating ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                      Generating...
                    </>
                  ) : (
                    <>
                      <Wand2Icon className="h-4 w-4 mr-2" />
                      Generate Content
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Content Output */}
          <div className="lg:col-span-2">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileTextIcon className="h-5 w-5" />
                  Generated Content
                </CardTitle>
                <CardDescription>
                  {content ? 'Review and edit your AI-generated content' : 'Your content will appear here after generation'}
                </CardDescription>
              </CardHeader>
              <CardContent>
                {content ? (
                  <div className="space-y-4">
                    <div className="p-4 bg-muted rounded-lg">
                      <h3 className="font-semibold text-lg mb-2">{title}</h3>
                      <div className="prose prose-sm max-w-none">
                        <p className="whitespace-pre-wrap">{content}</p>
                      </div>
                    </div>
                    
                    <div className="flex gap-2">
                      <Button onClick={handleSave}>
                        Save to Library
                      </Button>
                      <Button variant="outline">
                        Edit Content
                      </Button>
                      <Button variant="outline">
                        Regenerate
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <FileTextIcon className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                    <h3 className="text-lg font-semibold mb-2">Ready to generate content</h3>
                    <p className="text-muted-foreground mb-4">
                      Fill in the content brief and click "Generate Content" to get started
                    </p>
                    <Badge variant="secondary">
                      AI-powered content generation
                    </Badge>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}